apiVersion: batch/v1
kind: CronJob
metadata:
  name: msynbot.patrol-bot
  labels:
    name: msynbot.patrol-bot
    # The toolforge=tool label will cause $HOME and other paths to be mounted from Toolforge
    toolforge: tool
spec:
  schedule: "28 6 */4 * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            toolforge: tool
        spec:
          containers:
          - name: patrol-bot
            image: docker-registry.tools.wmflabs.org/toolforge-python39-sssd-base:latest
            workingDir: /data/project/msynbot/pywikibot_tasks/patrol_bot
            command: [ venv/bin/python3 ]
            args: [ main.py ]
            resources:
              requests:
                memory: "200Mi"
                cpu: "100m"
              limits:
                memory: "500Mi"
                cpu: "100m"
            env:
            - name: HOME
              value: /data/project/msynbot
            - name: PYTHONPATH
              value: /data/project/shared/pywikibot/stable
          restartPolicy: Never
